### ISSUE TITLE
Diagramme UML

### ISSUE THREAD

**Issue by Chrisserver** [Chrisserver/Gr17_IFT2255#4]
Diagramme de cas d'utilisation et scénarios
+ Besoins fonctionnels et interaction avec l'application

Diagramme d'activités
+ Flux d'activités de l'application couvrant les CUs des résidents uniquement

**Comment by Chrisserver** [comment]
J'avais déjà écrit des scénarios et commencé un Use Case, donc tu peux partir de ça si tu veux pour continuer

**Comment by RimElUdem** [comment]
Parfait merci je vais regarder ca!
